### ISSUE TITLE
Cannot pip install fbprophet - fails with SSLError in Anaconda / Python 3.6

### ISSUE THREAD

**Issue by mikhaildubov** [facebookincubator/prophet#114]
Here is what I get:

```
➜ pip install fbprophet
Collecting fbprophet
  Using cached fbprophet-0.1.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kwp4buip/fbprophet/setup.py", line 96, in <module>
        """
      File "/home/mikhaildubov/anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 315, in __init__
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 361, in fetch_build_eggs
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 851, in resolve
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1123, in best_match
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1135, in obtain
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 428, in fetch_build_egg
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 652, in easy_install
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 635, in fetch_distribution
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 616, in find
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 559, in download
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 804, in _download_url
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 810, in _attempt_download
      File "/home/mikhaildubov/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 725, in _download_to
      File "/home/mikhaildubov/anaconda3/lib/python3.6/http/client.py", line 449, in read
        n = self.readinto(b)
      File "/home/mikhaildubov/anaconda3/lib/python3.6/http/client.py", line 493, in readinto
        n = self.fp.readinto(b)
      File "/home/mikhaildubov/anaconda3/lib/python3.6/socket.py", line 586, in readinto
        return self._sock.recv_into(b)
      File "/home/mikhaildubov/anaconda3/lib/python3.6/ssl.py", line 1002, in recv_into
        return self.read(nbytes, buffer)
      File "/home/mikhaildubov/anaconda3/lib/python3.6/ssl.py", line 865, in read
        return self._sslobj.read(len, buffer)
      File "/home/mikhaildubov/anaconda3/lib/python3.6/ssl.py", line 625, in read
        v = self._sslobj.read(len, buffer)
    ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2178)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kwp4buip/fbprophet/
```

**Comment by bletham** [comment]
I don't have any idea what might be happening here. I wonder if it might be something in how Anaconda is configured? The best I could find is this SSL issue from Anaconda, which isn't exactly the same error but does have some steps at the bottom for updating SSL in Anaconda which would be worth trying:
https://github.com/conda/conda/issues/1624

**Comment by bletham** [comment]
I don't think there is anything to be fixed in Prophet for this.
