### ISSUE TITLE
Failed to build wheel for fbprophet with error "no suitable image found"

### ISSUE THREAD

**Issue by lyricat** [facebookincubator/prophet#125]
Hi there,

I met an error when I try to install fbprophet on my macOS. I tried to fix it but failed in the end. 

Could you please tell me how to resolve the problem? Thanks.

Env:
- Python 3.6.0
- macOS 10.12.3 

pystan:

```
~> pip show pystan
Name: pystan
Version: 2.14.0.0
Summary: Python interface to Stan, a package for Bayesian inference
Home-page: https://github.com/stan-dev/pystan
Author: PyStan Developers
Author-email: stan-users@googlegroups.com
License: GPLv3
Location: /usr/local/lib/python3.6/site-packages
Requires: Cython, numpy
```

cython:

```
~> pip show cython
Name: Cython
Version: 0.25.2
Summary: The Cython compiler for writing C extensions for the Python language.
Home-page: http://cython.org/
Author: Robert Bradshaw, Stefan Behnel, Dag Seljebotn, Greg Ewing, et al.
Author-email: cython-devel@python.org
License: Apache
Location: /usr/local/lib/python3.6/site-packages
Requires: 
```

Error messages:

```
...
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_models
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_35bf14a7f93814266f16b4cf48b40a5a NOW.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-build-r5hq0b9g/fbprophet/setup.py", line 96, in <module>
      """
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-build-r5hq0b9g/fbprophet/setup.py", line 20, in run
      self.build_stan_models()
    File "/private/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-build-r5hq0b9g/fbprophet/setup.py", line 32, in build_stan_models
      sm = StanModel(model_code=model_code)
    File "/usr/local/lib/python3.6/site-packages/pystan/model.py", line 315, in __init__
      self.module = load_module(self.module_name, lib_dir)
    File "/usr/local/lib/python3.6/site-packages/pystan/model.py", line 50, in load_module
      return __import__(module_name)
  ImportError: dlopen(/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/tmp1zq02xrx/stanfit4anon_model_35bf14a7f93814266f16b4cf48b40a5a_6964251626869176631.cpython-36m-darwin.so, 2): no suitable image found.  Did find:
  	/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/tmp1zq02xrx/stanfit4anon_model_35bf14a7f93814266f16b4cf48b40a5a_6964251626869176631.cpython-36m-darwin.so: mach-o, but built for simulator (not macOS)
  
  ----------------------------------------
  Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-build-r5hq0b9g/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-qm1ghugh-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_models
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_35bf14a7f93814266f16b4cf48b40a5a NOW.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-build-r5hq0b9g/fbprophet/setup.py", line 96, in <module>
        """
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-build-r5hq0b9g/fbprophet/setup.py", line 20, in run
        self.build_stan_models()
      File "/private/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-build-r5hq0b9g/fbprophet/setup.py", line 32, in build_stan_models
        sm = StanModel(model_code=model_code)
      File "/usr/local/lib/python3.6/site-packages/pystan/model.py", line 315, in __init__
        self.module = load_module(self.module_name, lib_dir)
      File "/usr/local/lib/python3.6/site-packages/pystan/model.py", line 50, in load_module
        return __import__(module_name)
    ImportError: dlopen(/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/tmp4qvnw3ji/stanfit4anon_model_35bf14a7f93814266f16b4cf48b40a5a_8830957315213382659.cpython-36m-darwin.so, 2): no suitable image found.  Did find:
    	/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/tmp4qvnw3ji/stanfit4anon_model_35bf14a7f93814266f16b4cf48b40a5a_8830957315213382659.cpython-36m-darwin.so: mach-o, but built for simulator (not macOS)
    
    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-build-r5hq0b9g/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-qm1ghugh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_9/fs1b5_4d13x2fd57hssvv7ph0000gq/T/pip-build-r5hq0b9g/fbprophet/
```

**Comment by bletham** [comment]
I'm not entirely sure what is going wrong here but the issue seems to be related to the C++ compiler being used by Stan. Can you check if PyStan is working at all or if the problem is specific to the Prophet model?

```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

**Comment by bletham** [comment]
If there are any further issues here please reopen, but I'm going to close for now.
