### ISSUE TITLE
fbprophet installation failed on ubuntu 16.04, with python 3.6

### ISSUE THREAD

**Issue by bharathgs** [facebookincubator/prophet#131]
I tried installing prophet many times via pip but the build fails.  
I've installed pystan.

this is what I get when I try to install fbprophet:  

 >  pip install fbprophet
Collecting fbprophet
  Using cached fbprophet-0.1.post1.tar.gz
Requirement already satisfied: pandas in ./applications/anaconda3/lib/python3.6/site-packages (from fbprophet)
Requirement already satisfied: pystan in ./applications/anaconda3/lib/python3.6/site-packages (from fbprophet)
Requirement already satisfied: python-dateutil>=2 in ./applications/anaconda3/lib/python3.6/site-packages (from pandas->fbprophet)
Requirement already satisfied: pytz>=2011k in ./applications/anaconda3/lib/python3.6/site-packages (from pandas->fbprophet)
Requirement already satisfied: numpy>=1.7.0 in ./applications/anaconda3/lib/python3.6/site-packages (from pandas->fbprophet)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in ./applications/anaconda3/lib/python3.6/site-packages (from pystan->fbprophet)
Requirement already satisfied: six>=1.5 in ./applications/anaconda3/lib/python3.6/site-packages (from python-dateutil>=2->pandas->fbprophet)
Building wheels for collected packages: fbprophet
  Running setup.py bdist_wheel for fbprophet ... error
  Complete output from command /home/xenomorph/applications/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-23wqosc9/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp13qaocsvpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_models
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_35bf14a7f93814266f16b4cf48b40a5a NOW.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-23wqosc9/fbprophet/setup.py", line 96, in <module>
      """
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-23wqosc9/fbprophet/setup.py", line 20, in run
      self.build_stan_models()
    File "/tmp/pip-build-23wqosc9/fbprophet/setup.py", line 32, in build_stan_models
      sm = StanModel(model_code=model_code)
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/pystan/model.py", line 315, in __init__
      self.module = load_module(self.module_name, lib_dir)
    File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/pystan/model.py", line 50, in load_module
      return __import__(module_name)
  ImportError: /tmp/tmpot24z08f/stanfit4anon_model_35bf14a7f93814266f16b4cf48b40a5a_8956272312002596876.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
  
  ----------------------------------------
  Failed building wheel for fbprophet

 >  Command "/home/xenomorph/applications/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-23wqosc9/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_epjkftx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-23wqosc9/fbprophet/

**Comment by NTAWolf** [comment]
@mingwandroid solved it for me: https://github.com/facebookincubator/prophet/issues/88#issuecomment-284686203
To recap, `conda install gcc`. Refresh your ENV to make sure `which gcc` gives you the Anaconda one, reinstall `pystan`, and install `fbprophet`.

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/0e76b79dde5ae8243a6ba4da1fa5ffe0bc748912 adds this tip to the install instructions and will hopefully help avoid this in the future, but reopen this if you are still having install issues!
