### ISSUE TITLE
KeyError: u'the label [Monday] is not in the [index]'

### ISSUE THREAD

**Issue by wyh10461** [facebookincubator/prophet#167]
Hi, 
  Thank you very much for providing this excellent tool. I'm running a prediction on weekly data and the first day of each week will be Saturday but not Sunday. 
  I ran the prediction without seeing any error till the last step on plot. Please help to debug it.
Thanks

  m.plot_components(forecast); 
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xyz2/anaconda/lib/python2.7/site-packages/fbprophet/forecaster.py", line 701, in plot_components
    y_weekly = [df_s.loc[d]['weekly'] for d in days]
  File "/Users/xyz2/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py", line 1312, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/Users/xyz2/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py", line 1482, in _getitem_axis
    self._has_valid_type(key, axis)
  File "/Users/xyz2/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py", line 1419, in _has_valid_type
    error()
  File "/Users/xyz2/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py", line 1406, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: u'the label [Monday] is not in the [index]'

**Comment by bletham** [comment]
This is a bug that was fixed in the Github version recently. If you download the code from the repository here and install it (`python setup.py install`) it should be work for you.

**Comment by seanjtaylor** [comment]
We'll be releasing the new bugfix very soon.  I'm going to close this out.
