### ISSUE TITLE
Can't install scrapy in WSL win 10

### ISSUE THREAD

**Issue by carlosgino** [facebookincubator/prophet#206]
I install devtools in linux by sudo apt-get install libmysqlclient-dev and then i want install scrapy... like about
gino69@LAPTOP-xxxx8:~$ pip install scrapy
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/gino69/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/home/gino69/.local/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

**Comment by carlosgino** [comment]
I install devtools in linux by sudo apt-get install libmysqlclient-dev and then i want install scrapy... like about

**Comment by carlosgino** [comment]
Sorry!!! That's ok. Scrapy was installed in my pc... thanks
