### ISSUE TITLE
`pip install fbprophet` fails in a fresh virtualenv

### ISSUE THREAD

**Issue by randlet** [facebookincubator/prophet#230]
If you create a fresh virtualenv and then `pip install fbprophet` the installation fails:

```
randlet@bohr ~  $ virtualenv virtualenvs/tmp
New python executable in /home/randlet/virtualenvs/tmp/bin/python
Installing setuptools, pip, wheel...done.

randlet@bohr ~  $ source virtualenvs/tmp/bin/activate

[tmp] randlet@bohr ~  $ which python && python -V
/home/randlet/virtualenvs/tmp/bin/python
Python 2.7.12

[tmp] randlet@bohr ~  $ pip install fbprophet
Collecting fbprophet
  Downloading fbprophet-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-A3ft5I/fbprophet/setup.py", line 126, in <module>
        """
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/setuptools/dist.py", line 377, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 852, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1124, in best_match
        return self.obtain(req, installer)
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1136, in obtain
        return installer(requirement)
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/setuptools/dist.py", line 445, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 880, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1119, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/randlet/virtualenvs/tmp/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1107, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with Cython>=0.22 and NumPy are required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-A3ft5I/fbprophet/

```

It's not a big deal to install the dependencies manually locally but it causes issues when installing multiple packages from a requirements file during deployments when/if the Prophet install craps out.  

I believe this is because of an issue with the `setup_requires` and `install_requires` settings in setup.py which I will submit a PR for.

**Comment by bletham** [comment]
Merged in https://github.com/facebookincubator/prophet/pull/231, thanks!
