### ISSUE TITLE
Pip Installation Fails on OSX

### ISSUE THREAD

**Issue by jengelman** [facebookincubator/prophet#245]
Running OSX 10.12.15, pip installation fails during pystan compilation with the following error message:

```
  Running setup.py install for fbprophet ... error
    Complete output from command /Users/joshengelman/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-vSOucl/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vEtyVF-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_models
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_7a788197ac3493030b72020b9ffdbe7d NOW.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-vSOucl/fbprophet/setup.py", line 126, in <module>
        """
      File "/Users/joshengelman/miniconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Users/joshengelman/miniconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Users/joshengelman/miniconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/joshengelman/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/install.py", line 61, in run
      File "/Users/joshengelman/miniconda2/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Users/joshengelman/miniconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Users/joshengelman/miniconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/joshengelman/miniconda2/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/Users/joshengelman/miniconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Users/joshengelman/miniconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-build-vSOucl/fbprophet/setup.py", line 46, in run
        build_stan_models(target_dir)
      File "/private/tmp/pip-build-vSOucl/fbprophet/setup.py", line 34, in build_stan_models
        sm = StanModel(model_code=model_code)
      File "/Users/joshengelman/miniconda2/lib/python2.7/site-packages/pystan/model.py", line 317, in __init__
        self.module = load_module(self.module_name, lib_dir)
      File "/Users/joshengelman/miniconda2/lib/python2.7/site-packages/pystan/model.py", line 54, in load_module
        return imp.load_module(module_name, *module_info)
    ImportError: dlopen(/tmp/tmpeCW1DR/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_8841191699184921746.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
      Referenced from: /tmp/tmpeCW1DR/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_8841191699184921746.so
      Expected in: flat namespace
     in /tmp/tmpeCW1DR/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_8841191699184921746.so
    
    ----------------------------------------
Command "/Users/joshengelman/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-vSOucl/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vEtyVF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-vSOucl/fbprophet/

```

**Comment by jengelman** [comment]
After some digging, issue is due to pystan failing to build the test script.  Fixed by installing the conda version of gcc
