### ISSUE TITLE
Problem with installation on Cent OS 7

### ISSUE THREAD

**Issue by beloteloff** [facebookincubator/prophet#247]
Hello, I can't install fbprophet on Cent OS, I see the mistake:
```
python3.4 setup.py install
running install
running bdist_egg
running egg_info
creating fbprophet.egg-info
writing requirements to fbprophet.egg-info/requires.txt
writing dependency_links to fbprophet.egg-info/dependency_links.txt
writing top-level names to fbprophet.egg-info/top_level.txt
writing fbprophet.egg-info/PKG-INFO
writing manifest file 'fbprophet.egg-info/SOURCES.txt'
reading manifest file 'fbprophet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'fbprophet/stan_models'
writing manifest file 'fbprophet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/fbprophet
creating build/lib/fbprophet/stan_models
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_7a788197ac3493030b72020b9ffdbe7d NOW.
Traceback (most recent call last):
  File "setup.py", line 123, in <module>
    """
  File "/usr/local/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.4/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.4/site-packages/setuptools/command/install.py", line 89, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 185, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 171, in call_command
    self.run_command(cmdname)
  File "/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.4/site-packages/setuptools/command/install_lib.py", line 20, in run
    self.build()
  File "/usr/local/lib/python3.4/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 46, in run
    build_stan_models(target_dir)
  File "setup.py", line 34, in build_stan_models
    sm = StanModel(model_code=model_code)
  File "/usr/local/lib/python3.4/site-packages/pystan/model.py", line 317, in __init__
    self.module = load_module(self.module_name, lib_dir)
  File "/usr/local/lib/python3.4/site-packages/pystan/model.py", line 50, in load_module
    return __import__(module_name)
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/tmp48d0l88u/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_3073237975369339339.cpython-34m.so)

I have parameters:
 gcc --version
gcc (GCC) 5.3.0

and after whereis gcc :
gcc: /usr/bin/gcc /usr/lib/gcc /usr/local/bin/gcc /usr/local/lib/gcc /usr/libexec/gcc /usr/share/man/man1/gcc.1.gz

**Comment by beloteloff** [comment]
But when I do yum install gcc:
gcc-4.8.5-11.el7.x86_64 already installed

**Comment by bletham** [comment]
Is Anaconda being used somewhere here? Can you try `sudo yum install libstdc++`?

**Comment by beloteloff** [comment]
libstdc++-4.8.5-11.el7.x86_64 already installed, I have no conda

**Comment by bletham** [comment]
hm, I'm not sure what is happening. This is a lame suggestion, but could you try re-installing pystan? And could you check if pystan is working correctly?
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

**Comment by beloteloff** [comment]
The same mistake:
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/pystan/model.py", line 317, in __init__
    self.module = load_module(self.module_name, lib_dir)
  File "/usr/local/lib/python3.4/site-packages/pystan/model.py", line 50, in load_module
    return __import__(module_name)
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/tmpuaayrj9r/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_8027217998870370281.cpython-34m.so)

**Comment by bletham** [comment]
So it looks like the version of libstdc++ that you have installed only includes up to GLIBCXX 3.4.19, and in particular does not include GLIBCXX 3.4.20 (hence the error):.

ftp://rpmfind.net/linux/RPM/centos/7.3.1611/x86_64/Packages/libstdc++-4.8.5-11.el7.i686.html

I'm not sure why pystan is expecting GLIBCXX 3.4.20, but could you try re-installing pytsan from source?
