### ISSUE TITLE
Installation problem on Windows 7

### ISSUE THREAD

**Issue by interphx** [facebookincubator/prophet#250]
I have Windows 7 x64 and use WinPython x64. During the installation, I see UnicodeDecodeError and WinError 32 (the message in Russian says "the file is already being used by another process").

```
D:\Software\WinPython64\scripts>pip install fbprophet --no-cache-dir
Collecting fbprophet
  Downloading fbprophet-0.1.1.tar.gz
Requirement already satisfied: matplotlib in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from fbprophet)
Requirement already satisfied: numpy in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from fbprophet)
Requirement already satisfied: pandas>=0.18.1 in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from fbprophet)
Requirement already satisfied: pystan>=2.14 in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from fbprophet)
Requirement already satisfied: pytz in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: cycler>=0.10 in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: python-dateutil in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: six>=1.10 in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in d:\software\winpython64\python-3.6.1.amd64\lib\site-packages (from pystan>=2.14->fbprophet)
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
Exception:
Traceback (most recent call last):
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 164: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 164: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\req\req_set.py", line 729, in cleanup_files
    req.remove_temporary_source()
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\req\req_install.py", line 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-build-jivgmwwr\\fbprophet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "D:\Software\WinPython64\python-3.6.1.amd64\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-build-jivgmwwr\\fbprophet'
```

**Comment by interphx** [comment]
Ok, this was related to [this pip bug](https://github.com/pypa/pip/issues/4251).
The solution mentioned there suggests to change 
 `s.decode('utf-8')` around line 75 in `Lib/site-packages/pip/compat/__init__.py`
to
`s.decode('your_console_encoding')`, and you can get your cmd's encoding by running `chcp` command.

I changed the encoding to cp866 in that line and installation completed successfully.
