### ISSUE TITLE
TypeError when fitting series of NaNs

### ISSUE THREAD

**Issue by DBCerigo** [facebookincubator/prophet#284]
Could be duplicate of #251 but getting different error, and similar issue to #258. Wanted to get it known before v0.2 is pushed.

When fitting on a series of all NaN values I'm getting
```
Traceback (most recent call last):
 ...
  File "<ipython-input-8-e06a84e7f481>", line 11, in process_page
    m.fit(traindf)
  File "/home/ubuntu/miniconda3/envs/basev1/lib/python3.6/site-packages/fbprophet/forecaster.py", line 486, in fit
    history = self.setup_dataframe(history, initialize_scales=True)
  File "/home/ubuntu/miniconda3/envs/basev1/lib/python3.6/site-packages/fbprophet/forecaster.py", line 179, in setup_dataframe
    df['t'] = (df['ds'] - self.start) / self.t_scale
  File "/home/ubuntu/miniconda3/envs/basev1/lib/python3.6/site-packages/pandas/core/ops.py", line 702, in wrapper
    converted = _Op.get_op(left, right, name, na_op)
  File "/home/ubuntu/miniconda3/envs/basev1/lib/python3.6/site-packages/pandas/core/ops.py", line 334, in get_op
    return _TimeOp(left, right, name, na_op)
  File "/home/ubuntu/miniconda3/envs/basev1/lib/python3.6/site-packages/pandas/core/ops.py", line 370, in __init__
    self._validate(lvalues, rvalues, name)
  File "/home/ubuntu/miniconda3/envs/basev1/lib/python3.6/site-packages/pandas/core/ops.py", line 409, in _validate
    "passed" % name)
TypeError: can only operate on a datetime with a rhs of a timedelta/DateOffset for addition and subtraction, but the operator [__truediv__] was passed
```
Wouldn't want to comment on how this case should be handled (i.e. whether to throw an error or return  a "model", though not sure what the most likely forecast is for something which you have no information about!)

**Comment by bletham** [comment]
Thanks for pointing this out, and just in time :-) https://github.com/facebookincubator/prophet/commit/439efb7209b775c42e1d6cc30cb8a660db6f8979 raises an error if less than 2 values in history or if future is empty.
