### ISSUE TITLE
Python 3.5 windows 10 plot_components ValueError: Invalid format string

### ISSUE THREAD

**Issue by dobbmeep** [facebookincubator/prophet#99]
There seems to be an issue with the strftime format (potentially '%s' usage)?

m.plot_components(forecast);
Traceback (most recent call last):
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-46-10d98d6d0e49>", line 1, in <module>
    m.plot_components(forecast);
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\fbprophet-0.1.post1-py3.5.egg\fbprophet\forecaster.py", line 674, in plot_components
    fig.tight_layout()
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\figure.py", line 1752, in tight_layout
    rect=rect)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\tight_layout.py", line 349, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\tight_layout.py", line 126, in auto_adjust_subplotpars
    tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots])
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\tight_layout.py", line 126, in <listcomp>
    tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots])
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axes\_base.py", line 3809, in get_tightbbox
    bb_xaxis = self.xaxis.get_tightbbox(renderer)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 1093, in get_tightbbox
    ticks_to_draw = self._update_ticks(renderer)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 969, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 969, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 916, in iter_ticks
    for i, val in enumerate(majorLocs)]
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 916, in <listcomp>
    for i, val in enumerate(majorLocs)]
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\dates.py", line 467, in __call__
    return self.strftime(dt, self.fmt)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\dates.py", line 571, in strftime
    return cbook.unicode_safe(dt.strftime(fmt))
ValueError: Invalid format string
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda2\envs\PWProd\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "C:\Anaconda2\envs\PWProd\lib\tkinter\__init__.py", line 596, in callit
    func(*args)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 370, in idle_draw
    self.draw()
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 351, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\backends\backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axes\_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 1136, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 969, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 969, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 916, in iter_ticks
    for i, val in enumerate(majorLocs)]
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\axis.py", line 916, in <listcomp>
    for i, val in enumerate(majorLocs)]
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\dates.py", line 467, in __call__
    return self.strftime(dt, self.fmt)
  File "C:\Anaconda2\envs\PWProd\lib\site-packages\matplotlib\dates.py", line 571, in strftime
    return cbook.unicode_safe(dt.strftime(fmt))
ValueError: Invalid format string

**Comment by Ffisegydd** [comment]
I've narrowed it down to the yearly plot in particular, the trend and weekly work fine (as separate plots).

The format string is `"%B %-d"`. I suspect it should be something like `"%B - %d"`?

**Comment by rjtavares** [comment]
@Ffisegydd, your suggestion worked for me.

**Comment by bletham** [comment]
The minus sign is to remove the leading 0 on the date. I wonder if it is failing because of a different package version. Can you check if it works just with `datetime`:
```
import datetime
d = datetime.date(year=2017, month=1, day=1)
d.strftime('%B %d')
d.strftime('%B %-d')
```
For me these both work in Pythons 2.17.13 and 3.5.3. What version of matplotlib do you have? Mine is 2.0.0rc2.

**Comment by rjtavares** [comment]
@bletham It fails with `datetime` also.

It's definitely a Windows thing: according to [this msdn page](https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx), the way to remove leading zeros in Windows is with `%#d`. This works for me:

```
>>> import datetime
>>> d = datetime.date(year=2017, month=1, day=1)
>>> d.strftime('%B %d')
'January 01'
>>> d.strftime('%B %#d')
'January 1'
```

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/1a6b736ccaa3d8adcbca45a16f25b8cc29777803 removes `%-d` and replaces it with an equivalent representation that should work in Windows. Could you install from Github and check that it is working now?

**Comment by rjtavares** [comment]
@bletham Works perfectly. Thanks!
